version: 2.1

jobs:
  ruby:
    docker:
      - image: rubylang/ruby:2.5.7-bionic
    steps:
      - run:
        name: Install System Dependencies
        # https://circleci.com/docs/2.0/custom-images/#required-tools-for-primary-containers
        command: apt-get update -y && apt-get install -y ssh
      - checkout
      - run:
          name: install and execute
          command: |
            gem install bundler -v 1.17.3
            bundle install
            bundle exec rake
            bundle exec rubocop
workflows:
  version: 2
  test:
    jobs:
      - ruby
