version: 2

jobs:
  ruby-2.5:
    docker:
      - image: ruby:2.5.7
    steps:
      - checkout
      - run:
        name: submodule update and execute
        command: |
          gem install bundler -v 1.17.3
          bundle install
          bundle exec rake
          bundle exec rubocop
workflows:
  version: 2
  test:
    jobs:
      - ruby-2.5
